[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3
no_match_contract = "SlowTest"
evm_version = 'osaka'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = './bin/solc-macos'
optimizer = true
optimizer_runs = 9999999
via_ir = true
ignored_error_codes = [2394, 6321, 3860, 5574]

[invariant]
fail_on_revert = true
runs = 1

[profile.ci]
verbosity = 3
solc = '0.8.31-pre.1'

# [profile.ci.fuzz]
# runs = 100000
# max_test_rejects = 500000

# [profile.ci.invariant]
# runs = 128

[profile.superfuzz]
verbosity = 3

[profile.superfuzz.fuzz]
runs = 1000000
max_test_rejects = 1000000

[profile.superfuzz.invariant]
runs = 1024

[profile.all_ticks]
no_match_contract = "n/a"
verbosity = 0
gas_limit = "18446744073709551615"
match_test = "test_all_tick_values"
match_contract = "SlowTestAllTicksTest"
